### PR TITLE
Visual improvements to the code, and organization in separate files

### PR DESCRIPTION
**Pull request by ignabelitzky**
Hi, I made some improvements with the code you provided of tic-tac-toe game.

- Now you have more files with the code.
- To update the screen I use the library nCurses so you don't see the historial of the boards or previous text.
- Makefile done to compile more easy the game.

It could be improved more in the future with a dynamic menu for example.
also you will need to install nCurses in your linux machine.

For example in Ubuntu you should install nCurses with these commands.
sudo apt update
sudo apt install libncurses5-dev
sudo apt install build-essential

Cheers and I hope you like the change.
Screenshot from 2024-02-29 23-34-01

### CODE REVIEW

**Comment by ignabelitzky** [comment]
As you can tell for the capture the design it's the same than before, but now you don't have all the previous prints from the board, with all the input. It updates the screen every time you make a play or insert some data like your name.

Try it please. Cheers!

**Comment by karts13** [comment]
Hi Ignacio/ignabelitzky,

First and foremost, I want to express my sincere gratitude for your time and effort in forking and enhancing my Tic Tac Toe game repository. Your contributions have added a new dimension to the project, and I truly appreciate your dedication to making it better.

Upon reviewing your pull request and testing the updated code, I noticed a minor issue that I believe needs clarification. In the modified version, it seems possible to add an 'X'/'O' to an already occupied square, which was not part of the intended gameplay in my original repository.

I would be grateful if you could take a moment to revisit that portion of the code and provide your insights on whether this behavior was intentional or unintentional. If it was intentional, could you please help me understand the rationale behind it? If it was unintentional, a small adjustment to ensure that players cannot add 'X'/'O' to an already occupied square would be fantastic.

Once again, I appreciate your valuable contributions to the project, and I'm looking forward to resolving this small hiccup together.

Best regards,
Karthik/karts13

**Comment by ignabelitzky** [comment]
Done, now it should work fine... please confirm.

**Comment by karts13** [comment]
Everything looks perfect!!!

**Pull request merged**
